### ISSUE TITLE
Better configurable map export

### ISSUE THREAD

**Issue by DeznekCZ** [sysoppl/Cities-Skylines-heightmap-generator#24]
Hello sysoppl,

I'm now using your heighmap generator and now I really missing more configurable map export,etc:
- map size
- forrest areas
- railway
- rivers
- hills (visible now)
- road colors

Thank you, DeznekCZ

**Comment by sysoppl** [comment]
![image](https://user-images.githubusercontent.com/30871217/136329535-98bc9655-acd6-4129-b2e3-37178fc61368.png)
Some of this options are already done. Heightmap will not export road colors or forrest areas - it's only exporting terrain data so later you can add there in game. If you mean something else please explain more. Thanks

**Comment by DeznekCZ** [comment]
I have created an issue which contains solution to get map in OSM format. If you are able to integrate it, will be usefull for players which are using OSM map importer.
[ISSUE 25](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/25)
[OpenStreetMap Import (WORKSHOP)](https://steamcommunity.com/sharedfiles/filedetails/?id=1957515502&searchtext=osm)

**Comment by nonta1234** [comment]
Hi
I use the Mapbox Static Images API to get map images, but I can't specify the zoom level when getting in the bounding box. I think you need to execute "getStaticImage" directly or another method to get it at the specified zoom level.
In addition, the maximum image size is 2560px (1280px @2x) due to the API specifications.

**Comment by sysoppl** [comment]
OSM export is implemented now.
