### ISSUE TITLE
Heightmaps generated are broken (completely black)

### ISSUE THREAD

**Issue by TooMuchFrixion** [sysoppl/Cities-Skylines-heightmap-generator#50]
The heightmaps generated have no whiteness or variation in their color. They are completely black.

**Comment by sysoppl** [comment]
Try to remove cache and use auto settings. I had black image and after hard refreshing the page it works again

**Comment by codythewolf** [comment]
I'm also currently running into this issue. Though it might be due to the area I'm trying to pull being parries with mountain, but I've tried in other, more mountainous area and get the same issue. I cleared my cache like you mentioned with no luck. I've tried it in incognito and even in another browser with no luck.
![NVanheight](https://user-images.githubusercontent.com/10508981/159134321-395c2f65-0d75-47a1-9d00-93ce354f68f1.png)
![NVanmap](https://user-images.githubusercontent.com/10508981/159134324-89d282ca-b7ca-46ac-a48f-8d71e3ded59e.png)

**Comment by AnotherVictim09** [comment]
I am also experiencing this issue - tried all the trouble shooting, cleared cache, hard refresh, etc, etc - no changes when downloading png, even tried other areas and no dice.

**Comment by DarwinDOS** [comment]
Same. I even try vpn, but it not help

**Comment by pjfournier** [comment]
I have noticed that when downloading the maps from Chrome I get a black box.  While with Firefox it works.  So I would recommend using Firefox with this app for the time being.

**Comment by sysoppl** [comment]
Hey. I updated API keys and reverted main version to older, more stable. Check if it is working now. Also check beta ( https://heightmap.skydark.pl/beta ) for the newer features.

**Comment by merket** [comment]
> I have noticed that when downloading the maps from Chrome I get a black box. While with Firefox it works. So I would recommend using Firefox with this app for the time being.

For me Firefox is broken and I  can only export using Edge and the image is still broken; very right side of the image, the last grid from top to bottom is darker than the rest, have to manually correct using editor but it's never the same as orijinal.

**Comment by sysoppl** [comment]
@merket have you tried https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/50#issuecomment-1104225139?
This problem occurs only in beta channel ( https://heightmap.skydark.pl/beta ). For main channel everything should work as intended. ( https://heightmap.skydark.pl )
