### ISSUE TITLE
the png or raw heightmaps are coming blank

### ISSUE THREAD

**Issue by lajimena** [sysoppl/Cities-Skylines-heightmap-generator#68]
I am a student of vfx in Vanarts, Vancouver, we used the heightmaps to create geometry in unreal last month. I tried to do it again yesterday and today, but the images came all black or all white. any help please?

**Comment by MadSynth** [comment]
I am also getting this same issue, on both the website and  locally downloaded version in Chrome. Just tried it on Microsoft Edge too. Same issue.
![heightmap (8)](https://user-images.githubusercontent.com/69952648/206407254-fa0c0cba-331a-4c17-b102-ba9645e17e03.png)

**Comment by sysoppl** [comment]
Looks like a problem with mapbox. Well, it's a paid service, and free tokens limits are used in 3 days here. Also, they probably changed something with API, because it gives me 404 error (Tile not found) but not everywhere. I can export files normally in Europe, San Francisco works also. Try other place in the world, or incognito mode.

If this is an issue with this tool - I'm not developing this anymore, just hosting, so until someone will create PR this probably won't work.
